server:
  port: 8080
spring:
  application:
    name: easyeat-food-delivery
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_eat
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  cache:
    redis:
      time-to-live: 1800000 # 设置有效期
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
upload-files-path: "E:\\Code\\Java\\easyeat-food-delivery\\upload-files\\"